{-# LANGUAGE OverloadedStrings #-}

module CddlAiken.Aiken.Cbor (
  cborLibrary,
)
where

import Data.Text (Text)
import Data.Text qualified as T

-- | The CBOR parsing library emitted into every generated Aiken project.
cborLibrary :: Text
cborLibrary =
  T.unlines
    [ "/// CBOR parsing result: value + next position"
    , "pub type ParseResult<a> {"
    , "  value: a,"
    , "  pos: Int,"
    , "}"
    , ""
    , "/// Read the additional info from a CBOR header byte."
    , "/// Returns (major_type, argument, next_position)."
    , "pub fn read_header(bytes: ByteArray, pos: Int) -> ParseResult<(Int, Int)> {"
    , "  let byte = builtin.index_bytearray(bytes, pos)"
    , "  let major = byte / 32"
    , "  let info = byte % 32"
    , "  if info < 24 {"
    , "    ParseResult { value: (major, info), pos: pos + 1 }"
    , "  } else if info == 24 {"
    , "    let arg = builtin.index_bytearray(bytes, pos + 1)"
    , "    ParseResult { value: (major, arg), pos: pos + 2 }"
    , "  } else if info == 25 {"
    , "    let b0 = builtin.index_bytearray(bytes, pos + 1)"
    , "    let b1 = builtin.index_bytearray(bytes, pos + 2)"
    , "    let arg = b0 * 256 + b1"
    , "    ParseResult { value: (major, arg), pos: pos + 3 }"
    , "  } else if info == 26 {"
    , "    let b0 = builtin.index_bytearray(bytes, pos + 1)"
    , "    let b1 = builtin.index_bytearray(bytes, pos + 2)"
    , "    let b2 = builtin.index_bytearray(bytes, pos + 3)"
    , "    let b3 = builtin.index_bytearray(bytes, pos + 4)"
    , "    let arg = b0 * 16777216 + b1 * 65536 + b2 * 256 + b3"
    , "    ParseResult { value: (major, arg), pos: pos + 5 }"
    , "  } else {"
    , "    fail @\"unsupported CBOR additional info\""
    , "  }"
    , "}"
    , ""
    , "/// Parse a CBOR unsigned integer (major type 0)"
    , "pub fn parse_uint(bytes: ByteArray, pos: Int) -> ParseResult<Int> {"
    , "  let ParseResult { value: (major, arg), pos } = read_header(bytes, pos)"
    , "  expect major == 0"
    , "  trace @\"expected uint (major type 0)\""
    , "  ParseResult { value: arg, pos }"
    , "}"
    , ""
    , "/// Parse a CBOR negative integer (major type 1)"
    , "pub fn parse_nint(bytes: ByteArray, pos: Int) -> ParseResult<Int> {"
    , "  let ParseResult { value: (major, arg), pos } = read_header(bytes, pos)"
    , "  expect major == 1"
    , "  trace @\"expected negative int (major type 1)\""
    , "  ParseResult { value: -1 - arg, pos }"
    , "}"
    , ""
    , "/// Parse a CBOR int (major type 0 or 1)"
    , "pub fn parse_int(bytes: ByteArray, pos: Int) -> ParseResult<Int> {"
    , "  let ParseResult { value: (major, arg), pos } = read_header(bytes, pos)"
    , "  if major == 0 {"
    , "    ParseResult { value: arg, pos }"
    , "  } else if major == 1 {"
    , "    ParseResult { value: -1 - arg, pos }"
    , "  } else {"
    , "    fail @\"expected int (major type 0 or 1)\""
    , "  }"
    , "}"
    , ""
    , "/// Parse a CBOR byte string (major type 2)"
    , "pub fn parse_bstr(bytes: ByteArray, pos: Int) -> ParseResult<ByteArray> {"
    , "  let ParseResult { value: (major, len), pos } = read_header(bytes, pos)"
    , "  expect major == 2"
    , "  trace @\"expected byte string (major type 2)\""
    , "  let value = builtin.slice_bytearray(pos, len, bytes)"
    , "  ParseResult { value, pos: pos + len }"
    , "}"
    , ""
    , "/// Parse a CBOR text string (major type 3)"
    , "pub fn parse_tstr(bytes: ByteArray, pos: Int) -> ParseResult<ByteArray> {"
    , "  let ParseResult { value: (major, len), pos } = read_header(bytes, pos)"
    , "  expect major == 3"
    , "  trace @\"expected text string (major type 3)\""
    , "  let value = builtin.slice_bytearray(pos, len, bytes)"
    , "  ParseResult { value, pos: pos + len }"
    , "}"
    , ""
    , "/// Parse a CBOR array header (major type 4)"
    , "pub fn parse_array_header(bytes: ByteArray, pos: Int) -> ParseResult<Int> {"
    , "  let ParseResult { value: (major, count), pos } = read_header(bytes, pos)"
    , "  expect major == 4"
    , "  trace @\"expected array (major type 4)\""
    , "  ParseResult { value: count, pos }"
    , "}"
    , ""
    , "/// Parse a CBOR map header (major type 5)"
    , "pub fn parse_map_header(bytes: ByteArray, pos: Int) -> ParseResult<Int> {"
    , "  let ParseResult { value: (major, count), pos } = read_header(bytes, pos)"
    , "  expect major == 5"
    , "  trace @\"expected map (major type 5)\""
    , "  ParseResult { value: count, pos }"
    , "}"
    , ""
    , "/// Parse a CBOR boolean (major type 7, values 20/21)"
    , "pub fn parse_bool(bytes: ByteArray, pos: Int) -> ParseResult<Bool> {"
    , "  let byte = builtin.index_bytearray(bytes, pos)"
    , "  if byte == 0xf4 {"
    , "    ParseResult { value: False, pos: pos + 1 }"
    , "  } else if byte == 0xf5 {"
    , "    ParseResult { value: True, pos: pos + 1 }"
    , "  } else {"
    , "    fail @\"expected boolean (0xf4 or 0xf5)\""
    , "  }"
    , "}"
    , ""
    , "/// Parse CBOR null (major type 7, value 22 = 0xf6)"
    , "pub fn parse_null(bytes: ByteArray, pos: Int) -> Int {"
    , "  let byte = builtin.index_bytearray(bytes, pos)"
    , "  expect byte == 0xf6"
    , "  trace @\"expected null (0xf6)\""
    , "  pos + 1"
    , "}"
    , ""
    , "/// Skip one CBOR value at the given position."
    , "pub fn skip_value(bytes: ByteArray, pos: Int) -> Int {"
    , "  let ParseResult { value: (major, arg), pos } = read_header(bytes, pos)"
    , "  if major == 0 || major == 1 {"
    , "    pos"
    , "  } else if major == 2 || major == 3 {"
    , "    pos + arg"
    , "  } else if major == 4 {"
    , "    skip_n(bytes, pos, arg)"
    , "  } else if major == 5 {"
    , "    skip_n(bytes, pos, arg * 2)"
    , "  } else if major == 7 {"
    , "    pos"
    , "  } else {"
    , "    fail @\"unsupported CBOR major type\""
    , "  }"
    , "}"
    , ""
    , "/// Skip n CBOR values sequentially"
    , "fn skip_n(bytes: ByteArray, pos: Int, n: Int) -> Int {"
    , "  if n == 0 {"
    , "    pos"
    , "  } else {"
    , "    let new_pos = skip_value(bytes, pos)"
    , "    skip_n(bytes, new_pos, n - 1)"
    , "  }"
    , "}"
    ]
